### PR TITLE
[RFC] Ability to controle the return flag

### PR DESCRIPTION
**Pull request by cmodijk**
Ability to controle the return flag from the event possible fix for #20 and #15. It's still an example implementation which needs test and some feedback.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
I'm not sure if this is the best solution yet. I prefer immutable events so my thoughts go towards a solution using decoration (wrapping the consumer, or creating a simple pipeline). Maybe it's too much though, not sure yet.

**Comment by cmodijk** [comment]
I prefer immutable events to and i personally would not use this solution. So if it's ok with @sroze we can close this.

**Comment by sroze** [comment]
Yup, I agree with @matthiasnoback. The way it's done now is the "Symfony way", and I'm not fond of too. Decorating the bus sounds good enough to me.

**Comment by cmodijk** [comment]
I just closed this we could always reopen the idea

**Pull request closed without merging**
