### PR TITLE
Support Symfony 3.0

### PR DESCRIPTION
**Pull request by ruudk**
This pull is waiting for https://github.com/videlalvaro/RabbitMqBundle/pull/313 to be merged and tagged.

I added my fork to the composer to see what Travis makes of it.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks, we'll wait a bit then :)

**Comment by cmodijk** [comment]
https://github.com/videlalvaro/RabbitMqBundle/pull/313 is merged :+1:

**Comment by ruudk** [comment]
Waiting for a tagged release, then this can be merged too!

**Comment by ruudk** [comment]
@matthiasnoback @cmodijk Version 1.8 is tagged. I updated this PR to use that version. After tests, this can be merged and tagged as well ;)

**Comment by matthiasnoback** [comment]
Well, do you _have_ to use 1.8? I think if we leave it as `~1.0`, it'll work too, since Composer will just find the version that works with Symfony 3.0, right? That way, people using Symfony ~2.0 can still use RabbitMQBundle ~1.0.

**Comment by ruudk** [comment]
You are right :) Fixed

**Comment by ruudk** [comment]
Can you tag it too?

**Comment by matthiasnoback** [comment]
Done!

**Comment by matthiasnoback** [comment]
And thanks for your work :)

**Comment by ruudk** [comment]
Ouch, it appears that the tests for this bundle are not correct. When running https://github.com/LongRunning/LongRunning/pull/15 tests it fails that the config is still not correct.

**Pull request merged**
