### PR TITLE
Use ProducerInterface to allow sandbox in OldSound RabbitMqBundle

### PR DESCRIPTION
**Pull request by notFloran**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
I like the idea, however - I also don't want to force users to upgrade to RabbitMQBundle 1.7 (which first contains `ProducerInterface`). Instead, it would be nice if you could just remove the type-hint of the constructor argument `$producer` and inside the constructor verify that it's either a `Producer` or a `Fallback` instance.

**Comment by matthiasnoback** [comment]
I guess that would do the trick, right?

**Comment by notFloran** [comment]
Yes, no problem with check in the constructor.

I fixed the code with your comments.

**Comment by matthiasnoback** [comment]
Thank you!

**Comment by matthiasnoback** [comment]
I also tagged v2.2.0.

**Comment by notFloran** [comment]
Thanks !

**Pull request merged**
