### PR TITLE
Travis > Test PHP 7.2

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by cmodijk** [comment]
@ruudk I merged this accidentally but there are error's event at the items that you did not touched
* https://travis-ci.org/SimpleBus/RabbitMQBundleBridge/builds/310889815

**Comment by ruudk** [comment]
I see, I will create a new PR to fix it.

**Comment by ruudk** [comment]
Not related to my change, but JMS seems to miss a dependency, see https://github.com/schmittjoh/JMSSerializerBundle/issues/624

**Comment by cmodijk** [comment]
@ruudk Thanks for looking into this

**Pull request merged**
