### PR TITLE
[RFC] Documentation how to handle failure

### PR DESCRIPTION
**Pull request by cmodijk**
I stated documenting way's of how to handle failed command's using this bundle. I'm not done with this yet but this is to let you know i'm working on it.

If you have any feedback please let me know.

### CODE REVIEW

**Comment by cmodijk** [comment]
I think the documentation is done.

**Comment by estevejm** [comment]
👍  useful!

**Comment by cmodijk** [comment]
I'm merging this now but this needs to move to the new docs

**Comment by cmodijk** [comment]
@geekdevs Can you add your configuration then i will check it in my testing setup.

**Comment by geekdevs** [comment]
@cmodijk I have configuration identical to yours here https://github.com/SimpleBus/RabbitMQBundleBridge/pull/23/commits/01f5411b2210e02893701225b77c8d1170c884ec. To be clear - I am trying to do "Auto retry" part.
I think this issue appears on latest versions of RabbitMQ as they implemented loop detection. I was testing with RabbitMQ 3.6.4

**Comment by cmodijk** [comment]
I'm currently working on a new project that uses 3.6.9 i will check if the retry part stil works in this project and will get back to you.

**Comment by cmodijk** [comment]
@geekdevs I'm sorry I intended to get back to you sooner. 

But I just tested this with the following config with `RabbitMQ 3.6.9` and the result is that ever 10 seconds (10000 milliseconds) the message is moved from the `asynchronous_commands_fallback` back to  `asynchronous_commands` when the handler trows an exception. I can also see that it has bean tried again and again (check the image).

The difference here is the `routing_keys` which needs to be set to  `routing_keys: ['#']` to except al the keys that are generated and the `type` to `topic`.

schermafbeelding 2017-05-30 om 14 15 56

```
old_sound_rabbit_mq:
    connections:
        default:
            host:                   '%rabbitmq_host%'
            port:                   '%rabbitmq_port%'
            vhost:                  '%rabbitmq_vhost%'
            user:                   '%rabbitmq_user%'
            password:               '%rabbitmq_password%'
            lazy:                   true
            keepalive:              true
    producers:
        asynchronous_commands:
            connection:             default
            exchange_options:       { name: 'asynchronous_commands', type: topic }
        asynchronous_events:
            connection:             default
            exchange_options:       { name: 'asynchronous_events', type: topic }
    consumers:
        # Fallback
        asynchronous_commands_fallback:
            connection:             default
            exchange_options:       { name: 'asynchronous_commands_fallback', type: topic }
            queue_options:          { name: 'asynchronous_commands_fallback', routing_keys: ['#'], arguments: {'x-dead-letter-exchange': ['S', 'asynchronous_commands'], 'x-message-ttl': ['I', 10000]} }
            callback:               'simple_bus.rabbit_mq_bundle_bridge.commands_consumer'
            qos_options:            { prefetch_size: 0, prefetch_count: 10, global: false }
        asynchronous_events_fallback:
            connection:             default
            exchange_options:       { name: 'asynchronous_events_fallback', type: topic }
            queue_options:          { name: 'asynchronous_events_fallback', routing_keys: ['#'], arguments: {'x-dead-letter-exchange': ['S', 'asynchronous_events'], 'x-message-ttl': ['I', 10000]} }
            callback:               'simple_bus.rabbit_mq_bundle_bridge.commands_consumer'
            qos_options:            { prefetch_size: 0, prefetch_count: 10, global: false }

       # Default
        asynchronous_commands:
            connection:             default
            exchange_options:       { name: 'asynchronous_commands', type: topic }
            queue_options:          { name: 'asynchronous_commands', routing_keys: [''], arguments: {'x-dead-letter-exchange': ['S', 'asynchronous_commands_fallback']} }
            callback:               'simple_bus.rabbit_mq_bundle_bridge.commands_consumer'
            qos_options:            { prefetch_size: 0, prefetch_count: 10, global: false }
        asynchronous_events:
            connection:             default
            exchange_options:       { name: 'asynchronous_events', type: topic }
            queue_options:          { name: 'asynchronous_events', routing_keys: [''], arguments: {'x-dead-letter-exchange': ['S', 'asynchronous_events_fallback']} }
            callback:               'simple_bus.rabbit_mq_bundle_bridge.events_consumer'
            qos_options:            { prefetch_size: 0, prefetch_count: 10, global: false }
```

Note:
- Normally I configure the `x-message-ttl` on `3600000` (expire once per hour) 

I created a issue to update the docs, thx for your comment and trying  this out.

**Pull request merged**
